### ISSUE TITLE
Gentoo build failure: DSO missing from command line

### ISSUE THREAD

**Issue by haasn** [slowmoVideo/slowmoVideo#53]
I'm trying to build slowmoVideo but I encounter various errors.

```
[00:35][nand@nanodesu:staff_r][~/dev/slowmoVideo/build][master 8200ce8=][127]
λ cmake ../src -DUSE_QTKIT=FALSE -DENABLE_TESTS=FALSE
-- Using qt5
Qt libraries found at : Qt5::Gui /  
-- checking: avformat.h
--           /usr/include/libavformat
-- checking: avcodec.h
--           /usr/include/libavcodec
-- checking: avutil.h
--           /usr/include/libavutil
-- checking: swscale.h
--           /usr/include/libswscale
-- FFMPEG libraries are at /usr/lib64/libavformat.so;/usr/lib64/libavcodec.so;/usr/lib64/libavutil.so;/usr/lib64/libswscale.so
-- slowmoInfo Bundle will be :  =>  slowmoVideo 

======================V3D============================
* (info) Installation prefix: /usr/local.
         (Can be adjusted with -DCMAKE_INSTALL_PREFIX=your_path.  Default: .)
* (info) Shaders will be included in the binary: YES
         (Can be disabled with the cmake flag -DDISABLE_INCLUDE_SOURCE)
* (ok) OpenGL found in /usr/include: /usr/lib64/libGLU.so;/usr/lib64/libGL.so
* (ok) GLUT found in /usr/include: /usr/lib64/libglut.so;/usr/lib64/libXmu.so;/usr/lib64/libXi.so
* (ok) GLEW found at /usr/include/GL
* (ok) JPEG libraries found at /usr/include: /usr/lib64/libjpeg.so
* (ok) PNG libraries found at /usr/include;/usr/include
* V3D will be built:                        ---YES---
==================slowmoVideo========================
* (info) slowmoVideo installation goes to /usr/local.
         (Can be adjusted with -DCMAKE_INSTALL_PREFIX=your_path. Default is .)
* (ok) ffmpeg found at 
* (ok) OpenCV 3.0.0 found at .
* slowmoVideo will be built:                ---YES---
=======================END===========================

-- Configuring done
CMake Warning (dev) at V3D/Config/v3d_macros.cmake:36 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "V3d2" of target "slowmoFlowBuilder" does not exist.
Call Stack (most recent call first):
  V3D/Apps/GL/CMakeLists.txt:6 (add_v3d_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/nand/dev/slowmoVideo/build
[00:36][nand@nanodesu:staff_r][~/dev/slowmoVideo/build][master 8200ce8=]
λ make
[  1%] Generating moc_ffmpeg_writer.cpp
[  1%] Generating moc_imageDisplay.cpp
[  2%] Generating moc_combinedShortcuts.cpp
Scanning dependencies of target sVencode
[  3%] Building CXX object slowmoVideo/lib/CMakeFiles/sVflow.dir/flowField_sV.cpp.o
[  4%] Building CXX object slowmoVideo/lib/CMakeFiles/sVflow.dir/kernel_sV.cpp.o
[  5%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/defs_sV.cpp.o
[  5%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/glsl_shaders.cpp.o
[  5%] Building CXX object slowmoVideo/lib/CMakeFiles/sVflow.dir/flowRW_sV.cpp.o
[  5%] Building CXX object slowmoVideo/lib/CMakeFiles/sVinfo.dir/videoInfo_sV.cpp.o
[  5%] Building CXX object slowmoVideo/lib/CMakeFiles/sVflow.dir/flowTools_sV.cpp.o
Scanning dependencies of target sVgui
[  5%] Building CXX object slowmoVideo/lib/CMakeFiles/sVencode.dir/ffmpeg_writer.cpp.o
[  5%] Building CXX object slowmoVideo/libgui/CMakeFiles/sVgui.dir/imageDisplay.cpp.o
[  6%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/v3d_gpubase.cpp.o
/home/nand/dev/slowmoVideo/src/slowmoVideo/lib/ffmpeg_writer.cpp:70:0: warning: ignoring #pragma mark  [-Wunknown-pragmas]
 #pragma mark -
 ^
/home/nand/dev/slowmoVideo/src/slowmoVideo/lib/ffmpeg_writer.cpp:127:0: warning: ignoring #pragma mark  [-Wunknown-pragmas]
 #pragma mark -
 ^
/home/nand/dev/slowmoVideo/src/slowmoVideo/lib/ffmpeg_writer.cpp:128:0: warning: ignoring #pragma mark C [-Wunknown-pragmas]
 #pragma mark C bridge
 ^
[  6%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/v3d_gpuflow.cpp.o
[  7%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/v3d_gpucolorflow.cpp.o
[  8%] Building CXX object slowmoVideo/libgui/CMakeFiles/sVgui.dir/combinedShortcuts.cpp.o
[  9%] Linking CXX static library libsVflow.a
[  9%] Built target sVflow
[ 10%] Building CXX object slowmoVideo/lib/CMakeFiles/sVvis.dir/flowVisualization_sV.cpp.o
/home/nand/dev/slowmoVideo/src/V3D/GL/v3d_gpuflow.cpp:17:4: warning: ‘void {anonymous}::upsampleDisparities(unsigned int, unsigned int, float, V3D_GPU::RTT_Buffer&, V3D_GPU::RTT_Buffer&)’ defined but not used [-Wunused-function]
    upsampleDisparities(unsigned uvSrcTex, unsigned pSrcTex, float pScale,
    ^
/home/nand/dev/slowmoVideo/src/V3D/GL/v3d_gpuflow.cpp:67:4: warning: ‘void {anonymous}::upsampleBuffer(unsigned int, float, V3D_GPU::FrameBufferObject&)’ defined but not used [-Wunused-function]
    upsampleBuffer(unsigned srcTex, float scale, FrameBufferObject& dstFbo)
    ^
/home/nand/dev/slowmoVideo/src/V3D/GL/v3d_gpuflow.cpp:103:4: warning: ‘void {anonymous}::upsampleBuffers(unsigned int, unsigned int, float, float, V3D_GPU::FrameBufferObject&)’ defined but not used [-Wunused-function]
    upsampleBuffers(unsigned src1Tex, unsigned src2Tex, float scale1, float scale2,
    ^
[ 11%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/vector_sV.cpp.o
[ 11%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/v3d_gpupyramid.cpp.o
[ 12%] Building CXX object CMakeFiles/V3D.dir/V3D/Base/v3d_image.cpp.o
/home/nand/dev/slowmoVideo/src/V3D/GL/v3d_gpucolorflow.cpp:74:4: warning: ‘void {anonymous}::upsampleDisparities(unsigned int, unsigned int, unsigned int, float, V3D_GPU::RTT_Buffer&, V3D_GPU::RTT_Buffer&, V3D_GPU::RTT_Buffer&)’ defined but not used [-Wunused-function]
    upsampleDisparities(unsigned uvSrcTex, unsigned pSrcTex, unsigned qSrcTex, float pScale,
    ^
[ 13%] Building CXX object slowmoVideo/lib/CMakeFiles/sVencode.dir/video_enc.cpp.o
[ 13%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/shutter_sV.cpp.o
[ 14%] Building CXX object slowmoVideo/lib/CMakeFiles/sVinfo.dir/avconvInfo_sV.cpp.o
[ 14%] Linking CXX static library libsVvis.a
[ 14%] Built target sVvis
[ 14%] Building CXX object slowmoVideo/lib/CMakeFiles/sVencode.dir/moc_ffmpeg_writer.cpp.o
[ 15%] Building CXX object slowmoVideo/visualizeFlow/CMakeFiles/slowmoVisualizeFlow.dir/visualizeFlow.cpp.o
[ 15%] Building CXX object slowmoVideo/libgui/CMakeFiles/sVgui.dir/moc_imageDisplay.cpp.o
[ 16%] Building CXX object slowmoVideo/libgui/CMakeFiles/sVgui.dir/moc_combinedShortcuts.cpp.o
[ 17%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/intMatrix_sV.cpp.o
[ 17%] Linking CXX static library libV3D.a
[ 17%] Built target V3D
[ 18%] Building CXX object V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o
[ 18%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/interpolate_sV.cpp.o
[ 19%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/bezierTools_sV.cpp.o
[ 19%] Linking CXX static library libsVinfo.a
[ 20%] Linking CXX static library libsVencode.a
[ 20%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/sourceField_sV.cpp.o
[ 20%] Built target sVinfo
[ 20%] Built target sVencode
[ 21%] Building CXX object V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/__/__/__/slowmoVideo/lib/flowRW_sV.cpp.o
[ 21%] Building CXX object V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/__/__/__/slowmoVideo/lib/flowField_sV.cpp.o
[ 22%] Linking CXX executable slowmoVisualizeFlow
[ 22%] Built target slowmoVisualizeFlow
[ 23%] Linking CXX static library libsVgui.a
[ 23%] Linking CXX executable slowmoFlowBuilder
[ 23%] Built target sVgui
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o: undefined reference to symbol 'XCreateColormap'
/usr/lib64/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[ 23%] Generating ui_flowEditCanvas.h
[ 25%] Generating ui_mainwindow.h
V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/build.make:154: recipe for target 'V3D/Apps/GL/slowmoFlowBuilder' failed
make[2]: *** [V3D/Apps/GL/slowmoFlowBuilder] Error 1
CMakeFiles/Makefile2:848: recipe for target 'V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/all' failed
make[1]: *** [V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 24%] Generating ui_shortcutListDialog.h
[ 26%] Generating moc_mainwindow.cpp
[ 27%] Generating moc_flowEditCanvas.cpp
[ 27%] Generating moc_shortcutListDialog.cpp
Scanning dependencies of target slowmoFlowEdit
[ 27%] Building CXX object slowmoVideo/slowmoFlowEdit/CMakeFiles/slowmoFlowEdit.dir/main.cpp.o
[ 28%] Building CXX object slowmoVideo/slowmoFlowEdit/CMakeFiles/slowmoFlowEdit.dir/mainwindow.cpp.o
[ 29%] Building CXX object slowmoVideo/slowmoFlowEdit/CMakeFiles/slowmoFlowEdit.dir/moc_shortcutListDialog.cpp.o
[ 30%] Building CXX object slowmoVideo/slowmoFlowEdit/CMakeFiles/slowmoFlowEdit.dir/moc_mainwindow.cpp.o
[ 31%] Building CXX object slowmoVideo/slowmoFlowEdit/CMakeFiles/slowmoFlowEdit.dir/shortcutListDialog.cpp.o
[ 31%] Building CXX object slowmoVideo/slowmoFlowEdit/CMakeFiles/slowmoFlowEdit.dir/flowEditCanvas.cpp.o
[ 31%] Building CXX object slowmoVideo/slowmoFlowEdit/CMakeFiles/slowmoFlowEdit.dir/moc_flowEditCanvas.cpp.o
[ 32%] Linking CXX static library libsV.a
[ 32%] Built target sV
[ 32%] Linking CXX executable slowmoFlowEdit
[ 32%] Built target slowmoFlowEdit
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[00:36][nand@nanodesu:staff_r][~/dev/slowmoVideo/build][master 8200ce8=][2]
λ 
```

If I restart manually, I also get the following error:
```
Scanning dependencies of target sVproj
[ 37%] Built target slowmoVideoInfo
[ 38%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o
[ 40%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/nodeList_sV.cpp.o
[ 38%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/segment_sV.cpp.o
[ 39%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/renderPreferences_sV.cpp.o
[ 41%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/node_sV.cpp.o
[ 41%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/tag_sV.cpp.o
[ 41%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/projectPreferences_sV.cpp.o
In file included from /home/nand/dev/slowmoVideo/src/slowmoVideo/project/project_sV.cpp:16:0:
/home/nand/dev/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.h:23:35: fatal error: opencv2/core/gpumat.hpp: No such file or directory
 #include "opencv2/core/gpumat.hpp"
                                   ^
compilation terminated.
slowmoVideo/project/CMakeFiles/sVproj.dir/build.make:90: recipe for target 'slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o' failed
make[2]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 41%] Linking CXX executable slowmoInfo
[ 42%] Built target slowmoInfo
[ 42%] Linking CXX executable slowmoInterpolate
[ 42%] Built target slowmoInterpolate
CMakeFiles/Makefile2:391: recipe for target 'slowmoVideo/project/CMakeFiles/sVproj.dir/all' failed
make[1]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

What am I doing wrong?

**Comment by valgit** [comment]
there seem to miss some librairies in linking .... did you have installed opencv and X11 development librairies ?

**Comment by haasn** [comment]
Yes, I have development libraries available for both, along with everything else on my system. Also, the ```cmake``` configuration step passed successfully.

More precisely, I have media-libs/opencv-3.0.0 and x11-libs/libX11-1.6.3 installed.

**Comment by valgit** [comment]
from your logs you seems to be missing some libraries ( "undefined reference to symbol 'XCreateColormap'" which came from X11-dev ) , can you check you have them, and maybe run the make in verbose and/or debug to see what the command line is ?

**Comment by pmo-19** [comment]
I think you may suffer from the same deficiency I had some days ago. See Issue `Undefined reference to symbol 'XCreateWindow'`

The file src/CMakeLists.txt was not listing `X11` as part of the set of the `target_link_libraries` . Therefore shared libraries (of the project) were not build against the `X11 library`.

I pushed a pull request today which was accepted and merged in the project. Which seems to close this issue.

Would you like to test the newly merged repository ? and tell us if it solves your problem ?

**Comment by haasn** [comment]
After pulling from master and trying again, the first error is indeed eliminated, but the second one was still present. Since gpumat.hpp did not seem to exist on my system at all, I tried downgrading opencv from 3.0.0 to 2.4.10.

After that, it complained about not finding "opencv2/ocl/ocl.hpp", which also does not seem to exist on my system. (I found "opencv2/nonfree/ocl.hpp", but that one itself imports "opencv2/ocl/ocl.hpp" and doesn't seem to be the same file at all)

This one is probably a Gentoo-specific issue, so I'll take it there instead.

**Comment by pmo-19** [comment]
OK. In Debian / Ubuntu the file `gpumat.hpp` you mentioned as missing on your system is part of either package `libopencv-core-dev` or package `libopencv-gpu-dev`.

See http://packages.ubuntu.com/search?searchon=contents&keywords=gpumat.hpp&mode=exactfilename&suite=trusty&arch=any

May be consider adding a dependence in your build or make sure you have this installed / build appropriately. These packages are part of `opencv`. As well you may consider to build `opencv` from the latest source and make sure you are not missing anything. As in Gentoo I know there is no packages and everything is compiled and build locally.

**Comment by pmo-19** [comment]
OK. In Debian / Ubuntu the file `gpumat.hpp` you mentioned as missing on your system is part of either package `libopencv-core-dev` or package `libopencv-gpu-dev`.

See http://packages.ubuntu.com/search?searchon=contents&keywords=gpumat.hpp&mode=exactfilename&suite=trusty&arch=any

May be consider adding a dependence in your build or make sure you have this installed / build appropriately. These packages are part of `opencv`. As well you may consider to build `opencv` from the latest source and make sure you are not missing anything. As in Gentoo I know there is no packages and everything is compiled and build locally.

Anyway all includes files are part of the source itself. I have open 2.4.9 in my Ubuntu system and `gpumat.hpp` appears twice in the source:

`opencv-2.4.9+dfsg/modules/core/include/opencv2/core`
`opencv-2.4.9+dfsg/modules/gpu/include/opencv2/gpu`

**Comment by valgit** [comment]
did you check like issue #68

**Comment by EoD** [comment]
I am pretty sure the issue here is fixed by now. Compiling seems to be fine and  the ``gpumat.hpp`` does belong to the opencv package:

```
$ equery b /usr/include/opencv2/gpu/gpumat.hpp
 * Searching for /usr/include/opencv2/gpu/gpumat.hpp ... 
media-libs/opencv-2.4.13 (/usr/include/opencv2/gpu/gpumat.hpp)
```
